#!/usr/bin/env python3
"""
Generate packet-6 (gate-align 8 slots) and packet-6B (representation-robustness 8 slots)
training yamls from their anchor bases. One-shot generator; not intended to be re-run.

Bases:
  - R13_RLP5_07_E3_seedB.yaml — packet-5 leader; anchor for packet-6 slots 1-7 and all of packet-6B.
  - R13_RLP5_08_E1_teams2_5.yaml — E1 control; anchor for packet-6 slot 8.
  - R13_RLP6_01_gate_align_canary.yaml — canary (already written by hand); anchor for slots 4-7.

Each slot is generated by applying text-level deltas relative to its base.
"""

from __future__ import annotations

from pathlib import Path

EXP_DIR = Path("experiments/phase2_round13")
BASE_07 = (EXP_DIR / "R13_RLP5_07_E3_seedB.yaml").read_text()
BASE_08 = (EXP_DIR / "R13_RLP5_08_E1_teams2_5.yaml").read_text()
CANARY = (EXP_DIR / "R13_RLP6_01_gate_align_canary.yaml").read_text()


AVSPEECH_VCD_BLOCK = """    external_real_sources:
      - bucket: "effort-collected-data"
        prefix: "real/external_youtube_avspeech"
        method: "external_youtube_avspeech"
        grouping: "by_folder"
        max_videos: 200
        deterministic: true
      - bucket: "effort-collected-data"
        prefix: "real/VCD"
        method: "zoom_vcd_real"
        grouping: "per_image"
        max_videos: 300
        deterministic: true
      - bucket: "live-deepfake-methods-real-and-fake-frames-cropped-teams-v2"
        prefix: "samples"
        method: "teams_ood_real"
        grouping: "by_folder"
        path_contains: "/frames/real/"
        video_id_depth: -4
        max_videos: 300
        deterministic: true"""

TEAMS_ONLY_REAL_BLOCK = """    external_real_sources:
      - bucket: "live-deepfake-methods-real-and-fake-frames-cropped-teams-v2"
        prefix: "samples"
        method: "teams_ood_real"
        grouping: "by_folder"
        path_contains: "/frames/real/"
        video_id_depth: -4
        max_videos: 300
        deterministic: true"""

WMA_TEAMS_FAKE_BLOCK = """    external_fake_sources:
      - bucket: "effort-collected-data"
        prefix: "wma_validation/enhanced_fake"
        method: "wma_failure_fake"
        grouping: "per_image"
        max_videos: 1202
        deterministic: true
      - bucket: "live-deepfake-methods-real-and-fake-frames-cropped-teams-v2"
        prefix: "samples"
        method: "teams_ood_fake"
        grouping: "by_folder"
        path_contains: "/frames/fake/"
        video_id_depth: -4
        max_videos: 300
        deterministic: true"""

WMA_TEAMS_FAKE_BLOCK_HINT_CLEAN = """    external_fake_sources:
      - bucket: "effort-collected-data"
        prefix: "wma_validation/enhanced_fake"
        method: "wma_failure_fake"
        grouping: "per_image"
        max_videos: 1202
        deterministic: true
      - bucket: "live-deepfake-methods-real-and-fake-frames-cropped-teams-v2"
        prefix: "samples"
        method: "teams_ood_fake"
        grouping: "by_folder"
        path_contains: "/frames/fake/"
        path_exclude_contains: ["/visomaster_"]
        video_id_depth: -4
        max_videos: 300
        deterministic: true"""

TEAMS_ONLY_FAKE_BLOCK_CLEAN = """    external_fake_sources:
      - bucket: "live-deepfake-methods-real-and-fake-frames-cropped-teams-v2"
        prefix: "samples"
        method: "teams_ood_fake"
        grouping: "by_folder"
        path_contains: "/frames/fake/"
        path_exclude_contains: ["/visomaster_"]
        video_id_depth: -4
        max_videos: 300
        deterministic: true"""

TEAMS_ONLY_FAKE_BLOCK_WITH_WMA = """    external_fake_sources:
      - bucket: "effort-collected-data"
        prefix: "wma_validation/enhanced_fake"
        method: "wma_failure_fake"
        grouping: "per_image"
        max_videos: 1202
        deterministic: true
      - bucket: "live-deepfake-methods-real-and-fake-frames-cropped-teams-v2"
        prefix: "samples"
        method: "teams_ood_fake"
        grouping: "by_folder"
        path_contains: "/frames/fake/"
        video_id_depth: -4
        max_videos: 300
        deterministic: true"""

EXPECTED_COUNTS_OLD = """    expected_counts:
      external_youtube_avspeech: 200
      zoom_vcd_real: 300
      wma_failure_fake: 1202
    strict_expected_counts: false"""

EXPECTED_COUNTS_NEW = """    expected_counts:
      teams_ood_real: 300
      teams_ood_fake: 300
    strict_expected_counts: false"""

EXPECTED_COUNTS_DROP_WMA = """    expected_counts:
      external_youtube_avspeech: 200
      zoom_vcd_real: 300
    strict_expected_counts: false"""


def replace_name_desc_tags(yaml: str, new_name: str, new_desc: str, extra_tags: list[str]) -> str:
    # Replace name and description (the first occurrences are the slot-level ones)
    import re
    yaml = re.sub(r'^name: "[^"]*"', f'name: "{new_name}"', yaml, count=1, flags=re.MULTILINE)
    yaml = re.sub(r'^description: "[^"]*"', f'description: "{new_desc}"', yaml, count=1, flags=re.MULTILINE)
    # Rewrite wandb.tags line: replace "packet-5"/"rlp5" with "packet-6"/"rlp6" and append extras
    # Simplest: find the wandb.tags line and append extras before the final ]
    def tag_sub(m):
        tags_inner = m.group(1)
        # Strip packet-5/rlp5 markers
        tags_inner = tags_inner.replace('"packet-5"', '"packet-6"').replace('"rlp5"', '"rlp6"')
        extra_str = ", ".join(f'"{t}"' for t in extra_tags)
        return f"tags: [{tags_inner}, {extra_str}]"
    yaml = re.sub(r'tags: \[(.+?)\]', tag_sub, yaml, count=1, flags=re.DOTALL)
    return yaml


def write_yaml(filename: str, content: str) -> None:
    out = EXP_DIR / filename
    out.write_text(content)
    print(f"  wrote {out}")


# ============================================================================
# Packet-6 slots
# ============================================================================

# Slot 2: hint_clean_only — base RLP5_07 + add path_exclude_contains to teams_ood_fake only.
s2 = BASE_07.replace(WMA_TEAMS_FAKE_BLOCK, WMA_TEAMS_FAKE_BLOCK_HINT_CLEAN)
s2 = replace_name_desc_tags(
    s2,
    "R13_RLP6_02_hint_clean_only",
    "Packet 6 — isolate hint-contamination lever. Add path_exclude_contains: ['/visomaster_'] to teams_ood_fake; KEEP avspeech+VCD in real gate and KEEP wma_failure_fake. Hypothesis: hint-clean alone swings composite by ≤0.01.",
    ["packet-6", "rlp6", "hint-clean-only", "ablation"],
)
s2 = s2.replace(
    "# Delta from base (this slot):\n"
    "# Packet 5 E3 core seed replication — identical to RLP5_01 but top-level seed 737->742 (split_seed and identity_split_seed stay 737 to preserve the train/held-out identity partition).",
    "# Delta from base (R13_RLP5_07_E3_seedB):\n"
    "# Packet-6 slot 2 — add path_exclude_contains: ['/visomaster_'] to teams_ood_fake only.\n"
    "# Isolates whether hint contamination materially depresses composite. Expect swing ≤0.01.",
)
write_yaml("R13_RLP6_02_hint_clean_only.yaml", s2)

# Slot 3: drop_wma_only — base RLP5_07 - wma_failure_fake
s3 = BASE_07.replace(WMA_TEAMS_FAKE_BLOCK, TEAMS_ONLY_FAKE_BLOCK_WITH_WMA.replace(
    # Actually we want to drop wma, so result = just teams_ood_fake (no wma, no hint exclude)
    "      - bucket: \"effort-collected-data\"\n"
    "        prefix: \"wma_validation/enhanced_fake\"\n"
    "        method: \"wma_failure_fake\"\n"
    "        grouping: \"per_image\"\n"
    "        max_videos: 1202\n"
    "        deterministic: true\n",
    "",
))
s3 = s3.replace(EXPECTED_COUNTS_OLD, EXPECTED_COUNTS_DROP_WMA)
s3 = replace_name_desc_tags(
    s3,
    "R13_RLP6_03_drop_wma_only",
    "Packet 6 — isolate wma drop. Remove wma_failure_fake from external_fake_sources; KEEP avspeech+VCD in real gate and KEEP hints in teams_ood_fake. Hypothesis: wma is not a gate driver, composite stays ~0.77.",
    ["packet-6", "rlp6", "drop-wma-only", "ablation"],
)
s3 = s3.replace(
    "# Delta from base (this slot):\n"
    "# Packet 5 E3 core seed replication — identical to RLP5_01 but top-level seed 737->742 (split_seed and identity_split_seed stay 737 to preserve the train/held-out identity partition).",
    "# Delta from base (R13_RLP5_07_E3_seedB):\n"
    "# Packet-6 slot 3 — remove wma_failure_fake from external_fake_sources only.\n"
    "# Isolates whether dropping wma changes composite. Expect no material movement.",
)
write_yaml("R13_RLP6_03_drop_wma_only.yaml", s3)

# Slot 4: add_enh_clean — canary + enable proper_visomaster_enhanced_clean lane + weight 2.0
PROPER_DATA_CLEAN_BLOCK = """  proper_data:
    enabled: true
    inventory_path: "arena/inventories/proper_visomaster_wave_2026_04_19_provisional.yaml"
    manifest_path: "arena/manifests/proper_visomaster_target_domain_manifest_2026-04-19_provisional.json"
    include_lanes:
      - "proper_visomaster_clean"
      - "proper_visomaster_teams"
      - "proper_visomaster_enhanced_teams"
    anchor_indices: [0, 2, 4, 6, 8, 10, 12, 14]"""

PROPER_DATA_PLUS_ENHANCED_CLEAN = """  proper_data:
    enabled: true
    inventory_path: "arena/inventories/proper_visomaster_wave_2026_04_19_provisional.yaml"
    manifest_path: "arena/manifests/proper_visomaster_target_domain_manifest_2026-04-19_provisional.json"
    include_lanes:
      - "proper_visomaster_clean"
      - "proper_visomaster_teams"
      - "proper_visomaster_enhanced_teams"
      - "proper_visomaster_enhanced_clean"
    anchor_indices: [0, 2, 4, 6, 8, 10, 12, 14]"""

FAMILY_WEIGHTS_BASE = """    family_weights:
      df40_fake: 0.15
      deeplive_non_enhanced_fake: 2.5
      deeplive_enhanced_fake: 3.0
      deeplive_teams_fake: 5.0
      proper_visomaster_clean_fake: 1.0
      proper_visomaster_teams_fake: 2.5
      proper_visomaster_enhanced_teams_fake: 1.0
      deeplive_teams_real: 4.0
      df40_real: 0.4
      realpool_real: 2.5
      external_real: 2.5"""

FAMILY_WEIGHTS_PLUS_ENHANCED_CLEAN_2 = """    family_weights:
      df40_fake: 0.15
      deeplive_non_enhanced_fake: 2.5
      deeplive_enhanced_fake: 3.0
      deeplive_teams_fake: 5.0
      proper_visomaster_clean_fake: 1.0
      proper_visomaster_teams_fake: 2.5
      proper_visomaster_enhanced_teams_fake: 1.0
      proper_visomaster_enhanced_clean_fake: 2.0
      deeplive_teams_real: 4.0
      df40_real: 0.4
      realpool_real: 2.5
      external_real: 2.5"""

FAMILY_WEIGHTS_PLUS_ENHANCED_CLEAN_4 = FAMILY_WEIGHTS_PLUS_ENHANCED_CLEAN_2.replace(
    "proper_visomaster_enhanced_clean_fake: 2.0",
    "proper_visomaster_enhanced_clean_fake: 4.0",
)

s4 = CANARY.replace(PROPER_DATA_CLEAN_BLOCK, PROPER_DATA_PLUS_ENHANCED_CLEAN)
s4 = s4.replace(FAMILY_WEIGHTS_BASE, FAMILY_WEIGHTS_PLUS_ENHANCED_CLEAN_2)
s4 = replace_name_desc_tags(
    s4,
    "R13_RLP6_04_add_enh_clean",
    "Packet 6 — canary levers + add proper_visomaster_enhanced_clean to training (weight 2.0). Hypothesis: the sharpest unused user-created fake source adds signal on top of gate alignment.",
    ["packet-6", "rlp6", "add-enh-clean", "proper-enhanced-clean-2_0"],
)
s4 = s4.replace(
    "# Hypothesis: deployment-aligned gate (teams_ood_* only) unblocks composite ≥ 0.88.\n"
    "# CANARY — launch alone first; confirm RUNNING + first-eval composite ≥ 0.85\n"
    "# before launching the rest of packet 6.",
    "# Delta from canary (R13_RLP6_01): add proper_visomaster_enhanced_clean lane + weight 2.0.\n"
    "# Hypothesis: adds signal on top of gate alignment.",
)
write_yaml("R13_RLP6_04_add_enh_clean.yaml", s4)

# Slot 5: seed_variance — canary + seed 742→745
s5 = CANARY.replace("seed: 742\n", "seed: 745\n")
s5 = replace_name_desc_tags(
    s5,
    "R13_RLP6_05_seed_variance",
    "Packet 6 — canary levers + seed 742→745. Seed-variance measurement on gate-aligned config.",
    ["packet-6", "rlp6", "seed-745", "seed-variance"],
)
s5 = s5.replace(
    "# CANARY — launch alone first; confirm RUNNING + first-eval composite ≥ 0.85\n"
    "# before launching the rest of packet 6.",
    "# Delta from canary (R13_RLP6_01): top-level seed 742→745 (split_seed, identity_split_seed\n"
    "# stay at 737 to preserve train/held-out identity partition).",
)
write_yaml("R13_RLP6_05_seed_variance.yaml", s5)

# Slot 6: avspeech_readout_only — canary + move avspeech+VCD to readout_only block.
# Current trainer has no readout_only block schema. Use a dedicated readout_only_sources list;
# if not supported, the trainer will ignore unknown keys (we'll fall back to same as canary).
# For now, represent as a side block that's not consumed by the gate.
s6 = CANARY.replace(
    "    # GATE ALIGNMENT (lever 1): avspeech + zoom_vcd dropped from real gate.\n"
    "    # Deployment target is Teams-passed reals — only teams_ood_real remains.\n"
    "    external_real_sources:\n"
    "      - bucket: \"live-deepfake-methods-real-and-fake-frames-cropped-teams-v2\"\n"
    "        prefix: \"samples\"\n"
    "        method: \"teams_ood_real\"\n"
    "        grouping: \"by_folder\"\n"
    "        path_contains: \"/frames/real/\"\n"
    "        video_id_depth: -4\n"
    "        max_videos: 300\n"
    "        deterministic: true",
    "    # GATE ALIGNMENT + readout-only observability: avspeech + zoom_vcd moved to\n"
    "    # readout_only_external_real_sources so their FPR is logged but does NOT gate τ.\n"
    "    # Note: readout_only block schema is a packet-6 convention; trainer ignores if\n"
    "    # unrecognized and this reduces to slot 1 behavior.\n"
    "    external_real_sources:\n"
    "      - bucket: \"live-deepfake-methods-real-and-fake-frames-cropped-teams-v2\"\n"
    "        prefix: \"samples\"\n"
    "        method: \"teams_ood_real\"\n"
    "        grouping: \"by_folder\"\n"
    "        path_contains: \"/frames/real/\"\n"
    "        video_id_depth: -4\n"
    "        max_videos: 300\n"
    "        deterministic: true\n"
    "\n"
    "    readout_only_external_real_sources:\n"
    "      - bucket: \"effort-collected-data\"\n"
    "        prefix: \"real/external_youtube_avspeech\"\n"
    "        method: \"external_youtube_avspeech\"\n"
    "        grouping: \"by_folder\"\n"
    "        max_videos: 200\n"
    "        deterministic: true\n"
    "      - bucket: \"effort-collected-data\"\n"
    "        prefix: \"real/VCD\"\n"
    "        method: \"zoom_vcd_real\"\n"
    "        grouping: \"per_image\"\n"
    "        max_videos: 300\n"
    "        deterministic: true",
)
s6 = replace_name_desc_tags(
    s6,
    "R13_RLP6_06_avspeech_readout_only",
    "Packet 6 — canary levers + move avspeech+VCD to readout-only block. Same gate as canary; preserves observability of avspeech/VCD FPR without them driving τ.",
    ["packet-6", "rlp6", "avspeech-readout-only", "observability"],
)
s6 = s6.replace(
    "# CANARY — launch alone first; confirm RUNNING + first-eval composite ≥ 0.85\n"
    "# before launching the rest of packet 6.",
    "# Delta from canary (R13_RLP6_01): avspeech + VCD moved to readout_only_external_real_sources.\n"
    "# Same gate semantics as canary; adds back observability of those pools' FPR.",
)
write_yaml("R13_RLP6_06_avspeech_readout_only.yaml", s6)

# Slot 7: heavy_enh — slot 4 + enhanced weight 2.0→4.0
s7 = s4.replace(FAMILY_WEIGHTS_PLUS_ENHANCED_CLEAN_2, FAMILY_WEIGHTS_PLUS_ENHANCED_CLEAN_4)
s7 = replace_name_desc_tags(
    s7,
    "R13_RLP6_07_heavy_enh",
    "Packet 6 — slot 4 + proper_visomaster_enhanced_clean weight 2.0→4.0. Saturation probe on the enhanced lane.",
    ["packet-6", "rlp6", "heavy-enh", "proper-enhanced-clean-4_0"],
)
s7 = s7.replace(
    "# Delta from canary (R13_RLP6_01): add proper_visomaster_enhanced_clean lane + weight 2.0.\n"
    "# Hypothesis: adds signal on top of gate alignment.",
    "# Delta from slot 4: proper_visomaster_enhanced_clean_fake weight 2.0→4.0.\n"
    "# Saturation probe on the enhanced lane.",
)
write_yaml("R13_RLP6_07_heavy_enh.yaml", s7)

# Slot 8: E1_gate_align — start from RLP5_08 (E1) + slot 1 gate changes
# Transform RLP5_08 gate block to look like canary's (drop avspeech+VCD, add hint-clean, drop wma).
s8 = BASE_08.replace(AVSPEECH_VCD_BLOCK, TEAMS_ONLY_REAL_BLOCK)
s8 = s8.replace(WMA_TEAMS_FAKE_BLOCK, TEAMS_ONLY_FAKE_BLOCK_CLEAN)
s8 = s8.replace(EXPECTED_COUNTS_OLD, EXPECTED_COUNTS_NEW)
s8 = replace_name_desc_tags(
    s8,
    "R13_RLP6_08_E1_gate_align",
    "Packet 6 — E1 base (RLP5_08) + canary gate changes. Confirms gate alignment works on simpler backbone.",
    ["packet-6", "rlp6", "e1-gate-align", "e1-control"],
)
# The BASE_08 comment block is RLP5-style; replace top comment header
import re as _re
s8 = _re.sub(
    r"^# ={5,}\n# R13_RLP5_08.*?^# ={5,}$",
    "# ============================================================================\n"
    "# R13_RLP6_08_E1_gate_align\n"
    "# Phase 2, Round 13 - relaunch packet 6.\n"
    "# Base = R13_RLP5_08_E1_teams2_5 (packet-5 E1 control, composite 0.7691 @ step 6500).\n"
    "# Applies slot-1 gate changes: drop avspeech+VCD from real gate, hint-clean teams_ood_fake, drop wma.\n"
    "# Hypothesis: gate alignment lifts E1 too, and E1 serves as a second anchor for packet 7.\n"
    "# ============================================================================",
    s8,
    count=1,
    flags=_re.MULTILINE | _re.DOTALL,
)
write_yaml("R13_RLP6_08_E1_gate_align.yaml", s8)


# ============================================================================
# Packet-6B slots — representation robustness
# All inherit from CANARY (slot-1 gate) unless otherwise noted.
# ============================================================================

def make_rlp6b(slot_id: str, name: str, desc: str, tags: list[str], mutator):
    """Generate an RLP6B yaml starting from the canary yaml.

    mutator takes the yaml text, returns modified text with the representation
    lever applied. name/desc/tags are applied via replace_name_desc_tags.
    """
    y = CANARY
    y = mutator(y)
    y = replace_name_desc_tags(y, name, desc, tags)
    # Rewrite top header
    y = _re.sub(
        r"^# ={5,}\n# R13_RLP6_01_gate_align_canary.*?^# ={5,}$",
        "# ============================================================================\n"
        f"# {name}\n"
        "# Phase 2, Round 13 - relaunch packet 6B (representation robustness).\n"
        "# Base = R13_RLP5_07_E3_seedB + packet-6 slot-1 gate-alignment changes.\n"
        f"# Representation lever: {desc}\n"
        "# ============================================================================",
        y,
        count=1,
        flags=_re.MULTILINE | _re.DOTALL,
    )
    write_yaml(f"{name}.yaml", y)


def add_quality_head_lambda(yaml: str, multiplier: float) -> str:
    """Enable quality-domain adversarial head and set its loss weight.

    Canary doesn't set this; default in detector is `use_quality_domain_head: False`.
    Enable explicitly + scale weight from the default 0.1. Note: requires the
    dataloader to provide `quality_domain` labels (see DOMAIN_MAP in
    effort_detector.py:250); if labels are missing the trainer raises unless
    quality_domain_require_labels is False — for an experiment we want strict.
    """
    weight = 0.1 * multiplier
    insertion = (
        f"use_quality_domain_head: true\n"
        f"quality_domain_loss_weight: {weight}\n"
        f"quality_domain_require_labels: true\n\n"
    )
    return yaml.replace("evaluate_every_steps: 500", insertion + "evaluate_every_steps: 500", 1)


def set_arcface_margin(yaml: str, new_m: float) -> str:
    return yaml.replace("arcface_m: 0.15", f"arcface_m: {new_m}")


def set_mixup_alpha(yaml: str, alpha: float) -> str:
    # Canary doesn't set mixup_alpha. Insert into the top-level training params area.
    return yaml.replace("stability_lambda: 0.0\n", f"stability_lambda: 0.0\nmixup_alpha: {alpha}\n", 1)


def set_label_smoothing_fake(yaml: str, smoothing: float) -> str:
    # Enable label_smoothing; configurable per-class support may not exist so use a uniform hyperparam
    # and document in desc that it applies to both classes in current codebase.
    return yaml.replace("label_smoothing: 0.0\n", f"label_smoothing: {smoothing}\n", 1)


def enable_feat_norm_reg(yaml: str, lam: float) -> str:
    insertion = f"feat_norm_reg_lambda: {lam}\n"
    return yaml.replace("stability_lambda: 0.0\n", f"stability_lambda: 0.0\n{insertion}", 1)


# RLP6B_01: quality_lambda_2x
make_rlp6b(
    "01", "R13_RLP6B_01_quality_lambda_2x",
    "quality_loss_weight × 2 — stronger gradient-reversal adversarial pressure on the backbone to forget capture-domain texture. Attacks the diagnosed low-norm+enhancement shortcut indirectly by weakening any domain-distinguishable feature.",
    ["packet-6b", "rlp6b", "quality-lambda-2x", "representation-robustness"],
    lambda y: add_quality_head_lambda(y, 2.0),
)

# RLP6B_02: quality_lambda_4x
make_rlp6b(
    "02", "R13_RLP6B_02_quality_lambda_4x",
    "quality_loss_weight × 4 — saturation probe on quality-adversarial. Tests whether stronger-still domain pressure further collapses the enhancement-vs-real distinction.",
    ["packet-6b", "rlp6b", "quality-lambda-4x", "representation-robustness"],
    lambda y: add_quality_head_lambda(y, 4.0),
)

# RLP6B_03: arcface_high_margin
make_rlp6b(
    "03", "R13_RLP6B_03_arcface_high_margin",
    "ArcFace margin m: 0.15→0.50. Tighter angular margin forces features into class-cluster geometry where feature-norm becomes less decision-relevant.",
    ["packet-6b", "rlp6b", "arcface-m-050", "representation-robustness"],
    lambda y: set_arcface_margin(y, 0.50),
)

# RLP6B_04: mixup_strong
make_rlp6b(
    "04", "R13_RLP6B_04_mixup_strong",
    "mixup_alpha 0.5 — heavy embedding interpolation between real/fake; flattens the low-norm 'fake' region by forcing convex combinations to live there too.",
    ["packet-6b", "rlp6b", "mixup-alpha-0_5", "representation-robustness"],
    lambda y: set_mixup_alpha(y, 0.5),
)

# RLP6B_05: label_smooth_fake
make_rlp6b(
    "05", "R13_RLP6B_05_label_smooth_fake",
    "label_smoothing 0.1 — softens the model's certainty in the confident-fake region. Attacks the 'super-confident low-norm = fake' shortcut by penalizing overconfidence.",
    ["packet-6b", "rlp6b", "label-smoothing-0_1", "representation-robustness"],
    lambda y: set_label_smoothing_fake(y, 0.1),
)

# RLP6B_06: feat_norm_reg
make_rlp6b(
    "06", "R13_RLP6B_06_feat_norm_reg",
    "feat_norm_reg_lambda 0.05 — direct aux loss penalizing (mean-feature-norm-real − mean-feature-norm-fake)² + variance penalty. Targets the diagnosed shortcut head-on. Requires detectors/effort_detector.py code change.",
    ["packet-6b", "rlp6b", "feat-norm-reg-0_05", "representation-robustness", "code-change"],
    lambda y: enable_feat_norm_reg(y, 0.05),
)

# RLP6B_07: combo_lite — quality_2x + arcface_m=0.30 + mixup=0.3
def combo_lite(y: str) -> str:
    y = add_quality_head_lambda(y, 2.0)
    y = set_arcface_margin(y, 0.30)
    y = set_mixup_alpha(y, 0.3)
    return y

make_rlp6b(
    "07", "R13_RLP6B_07_combo_lite",
    "Conservative multi-lever combo: quality_lambda_2x + arcface_m=0.30 + mixup_alpha=0.3. Tests if mid-strength combined pressure beats any single high-strength lever.",
    ["packet-6b", "rlp6b", "combo-lite", "representation-robustness"],
    combo_lite,
)

# RLP6B_08: combo_aggressive — quality_4x + arcface_m=0.50 + mixup=0.5 + feat_norm_reg=0.05
def combo_aggressive(y: str) -> str:
    y = add_quality_head_lambda(y, 4.0)
    y = set_arcface_margin(y, 0.50)
    y = set_mixup_alpha(y, 0.5)
    y = enable_feat_norm_reg(y, 0.05)
    return y

make_rlp6b(
    "08", "R13_RLP6B_08_combo_aggressive",
    "Aggressive multi-lever combo: quality_lambda_4x + arcface_m=0.50 + mixup_alpha=0.5 + feat_norm_reg=0.05. Maximum representation pressure; may regress baseline recall if over-regularized.",
    ["packet-6b", "rlp6b", "combo-aggressive", "representation-robustness", "code-change"],
    combo_aggressive,
)

print("\nDone. Generated 7 packet-6 yamls and 8 packet-6B yamls.")
