_wandb:
    value:
        cli_version: 0.21.0
        e:
            zmjfrkkovu1zerw6051aybx240trhl7x:
                codePath: DeepfakeBench/training/train_sweep.py
                codePathLocal: train_sweep.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "105426538496"
                        used: "33732878336"
                email: adammokiy@mail.tau.ac.il
                executable: /home/roee/repos/Effort-AIGI-Detection/effortvenv/bin/python
                git:
                    commit: 26503d3f7dc5baae2f2c6b0375c9a79cedd61a4d
                    remote: git@github.com:roeehub/Effort-AIGI-Detection.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-bbe38fe6-0662-d470-5bfb-a7e397d738c7
                host: live-df-demo
                memory:
                    total: "15728848896"
                os: Linux-5.10.0-35-cloud-amd64-x86_64-with-glibc2.31
                program: /home/roee/repos/Effort-AIGI-Detection/DeepfakeBench/training/train_sweep.py
                python: CPython 3.10.17
                root: /home/roee/repos/Effort-AIGI-Detection/DeepfakeBench/training
                startedAt: "2025-07-27T16:57:57.224252Z"
                writerId: zmjfrkkovu1zerw6051aybx240trhl7x
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 80
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 80
            "3":
                - 14
            "4": 3.10.17
            "5": 0.21.0
            "6": 4.21.0
            "12": 0.21.0
            "13": linux-x86_64
eps:
    value: 7.507177888500223e-06
lr:
    value: 0.00881639863912746
train_batchSize:
    value: 64
weight_decay:
    value: 0.001
