"""Parse the T4 promotion contract scorecard artifacts and emit a digest.

Reads from gs://training-job-outputs/test_results/teams_promotion_contract/
teams-promotion-contract-20260511-002920/promotion_contract/

Outputs:
  - analysis/cpu_diagnostics_2026-05-10/T4_SCORECARD_DIGEST_2026-05-11.md
  - prints a concise verdict to stdout

Designed for autonomous overnight invocation: surfaces (a) whether any
T4 ckpt formally promotes per the v3-fix policy, (b) per-ckpt rankings
on the lex policy, and (c) per-cell deltas vs P8A/E2B anchors.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path("/Users/roeedar/Documents/repos/Effort-AIGI-Detection-DtectVision/DeepfakeBench/training")
RESULTS_ROOT = "gs://training-job-outputs/test_results/teams_promotion_contract/teams-promotion-contract-20260511-002920"
OUT_MD = REPO_ROOT / "analysis/cpu_diagnostics_2026-05-10/T4_SCORECARD_DIGEST_2026-05-11.md"


def gs_cat(uri: str) -> str:
    return subprocess.check_output(["gsutil", "cat", uri], text=True)


def gs_ls(prefix: str) -> list[str]:
    try:
        return subprocess.check_output(["gsutil", "ls", prefix], text=True).strip().splitlines()
    except subprocess.CalledProcessError:
        return []


def fmt_metric(v, fmt=".3f"):
    if v is None:
        return "—"
    if isinstance(v, (int, float)):
        return f"{v:{fmt}}"
    return str(v)


def main():
    out_lines = []
    out_lines.append("# T4 Promotion Contract Scorecard — Digest")
    out_lines.append("")
    out_lines.append("Auto-generated by `digest_t4_scorecard.py` from `gs://training-job-outputs/test_results/teams_promotion_contract/teams-promotion-contract-20260511-002920/`.")
    out_lines.append("")

    contract_dir = f"{RESULTS_ROOT}/promotion_contract"
    diag_dir = f"{RESULTS_ROOT}/diagnostic_scorecard"

    files = gs_ls(contract_dir + "/")
    if not files:
        msg = f"No artifacts at {contract_dir}/ — scorecard may not have finished."
        print(msg)
        out_lines.append(f"⚠ {msg}")
        OUT_MD.write_text("\n".join(out_lines))
        return 1

    out_lines.append("## Files present in `promotion_contract/`")
    out_lines.append("")
    for f in files:
        out_lines.append(f"- `{f.replace(RESULTS_ROOT, '<root>')}`")
    out_lines.append("")

    # 1. promotion_winner.json — the verdict
    winner_uri = f"{contract_dir}/promotion_winner.json"
    if any(winner_uri == f for f in files):
        try:
            winner = json.loads(gs_cat(winner_uri))
            out_lines.append("## Promotion winner (formal verdict)")
            out_lines.append("")
            out_lines.append("```json")
            out_lines.append(json.dumps(winner, indent=2))
            out_lines.append("```")
            out_lines.append("")
            # Print to stdout too
            print("=" * 70)
            print("PROMOTION WINNER:")
            print(json.dumps(winner, indent=2))
            print("=" * 70)
        except Exception as e:
            out_lines.append(f"⚠ Failed to parse `promotion_winner.json`: {e}")

    # 2. promotion_contract.json — full per-ckpt breakdown
    contract_uri = f"{contract_dir}/promotion_contract.json"
    if any(contract_uri == f for f in files):
        try:
            contract = json.loads(gs_cat(contract_uri))
            out_lines.append("## Promotion contract — per-ckpt summary")
            out_lines.append("")
            # Try to extract per-ckpt rows in a generic way
            if isinstance(contract, dict):
                for k, v in contract.items():
                    if isinstance(v, list) and len(v) > 0 and isinstance(v[0], dict):
                        out_lines.append(f"### {k}")
                        out_lines.append("")
                        keys = list(v[0].keys())[:8]
                        out_lines.append("| " + " | ".join(keys) + " |")
                        out_lines.append("|" + "|".join(["---"] * len(keys)) + "|")
                        for row in v:
                            out_lines.append("| " + " | ".join(fmt_metric(row.get(k)) for k in keys) + " |")
                        out_lines.append("")
                    elif isinstance(v, dict):
                        out_lines.append(f"### {k}")
                        out_lines.append("")
                        out_lines.append("```json")
                        out_lines.append(json.dumps(v, indent=2)[:2000])
                        out_lines.append("```")
                        out_lines.append("")
        except Exception as e:
            out_lines.append(f"⚠ Failed to parse `promotion_contract.json`: {e}")

    # 3. checkpoint_summary.csv — concise table
    summary_uri = f"{contract_dir}/checkpoint_summary.csv"
    if any(summary_uri == f for f in files):
        try:
            content = gs_cat(summary_uri)
            out_lines.append("## checkpoint_summary.csv")
            out_lines.append("")
            out_lines.append("```")
            out_lines.append(content[:8000])
            out_lines.append("```")
            out_lines.append("")
            print()
            print("=" * 70)
            print("CHECKPOINT SUMMARY:")
            print(content[:4000])
            print("=" * 70)
        except Exception as e:
            out_lines.append(f"⚠ Failed to read `checkpoint_summary.csv`: {e}")

    # 4. selected_threshold_scorecard.csv — calibrated metrics at chosen τ
    sel_uri = f"{contract_dir}/selected_threshold_scorecard.csv"
    if any(sel_uri == f for f in files):
        try:
            content = gs_cat(sel_uri)
            out_lines.append("## selected_threshold_scorecard.csv (head, 4000 chars)")
            out_lines.append("")
            out_lines.append("```")
            out_lines.append(content[:4000])
            out_lines.append("```")
            out_lines.append("")
        except Exception as e:
            out_lines.append(f"⚠ Failed to read `selected_threshold_scorecard.csv`: {e}")

    # 5. diagnostic_scorecard/scorecard.json
    diag_uri = f"{diag_dir}/scorecard.json"
    diag_files = gs_ls(diag_dir + "/")
    if any(diag_uri == f for f in diag_files):
        try:
            diag = json.loads(gs_cat(diag_uri))
            out_lines.append("## diagnostic_scorecard/scorecard.json (top-level)")
            out_lines.append("")
            if isinstance(diag, dict):
                preview = {k: v for k, v in diag.items() if not isinstance(v, (list, dict)) or (isinstance(v, list) and len(v) < 20)}
                out_lines.append("```json")
                out_lines.append(json.dumps(preview, indent=2)[:3000])
                out_lines.append("```")
                out_lines.append("")
        except Exception as e:
            out_lines.append(f"⚠ Failed to parse `diagnostic_scorecard/scorecard.json`: {e}")

    OUT_MD.write_text("\n".join(out_lines))
    print(f"\nDigest written: {OUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
