"""Build a viewer-served INDEX.html summarizing the CPU follow-ups."""
import csv
from pathlib import Path

ANALYSIS_DIR = Path(__file__).parent
OUT_DIR = ANALYSIS_DIR / "outputs"
FIG_DIR = ANALYSIS_DIR / "figures"
RAW_DIR = ANALYSIS_DIR / "raw_reports"

# Asset URLs use /api/static-report-asset/<rel_path> where rel_path is relative to TRAINING_DIR/analysis/
def asset_url(p: Path) -> str:
    rel = p.relative_to(ANALYSIS_DIR.parent)  # relative to analysis/
    return f"/api/static-report-asset/{rel}"


def csv_to_html_table(csv_path: Path, max_rows: int = 200) -> str:
    if not csv_path.exists():
        return f"<p><em>Missing: {csv_path}</em></p>"
    rows = list(csv.DictReader(csv_path.open()))[:max_rows]
    if not rows:
        return "<p><em>(empty)</em></p>"
    headers = list(rows[0].keys())
    h = "<table><thead><tr>" + "".join(f"<th>{c}</th>" for c in headers) + "</tr></thead><tbody>"
    for r in rows:
        h += "<tr>"
        for c in headers:
            v = r[c]
            try:
                fv = float(v)
                v = f"{fv:.4f}" if abs(fv) < 1e6 else v
            except ValueError:
                pass
            h += f"<td>{v}</td>"
        h += "</tr>"
    h += "</tbody></table>"
    return h


def main():
    fake_suites = ["visomaster_enhanced_macro_dev", "deeplive_enhanced_dev", "teams_fake_all_dev", "teams_fake_all_lockbox"]
    all_suites = ["teams_real_all_dev", "teams_real_poor_quality_dev", "teams_real_lighting_extreme_dev",
                  "teams_real_all_lockbox", "teams_real_dor_dev"] + fake_suites

    html = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>E-packet CPU follow-ups (2026-05-04)</title>
<style>
  body { font-family: -apple-system, monospace; max-width: 1400px; margin: 1em auto; padding: 0 1em; }
  h1, h2, h3 { font-family: -apple-system; }
  h2 { border-bottom: 2px solid #333; padding-bottom: 0.2em; margin-top: 2em; }
  table { border-collapse: collapse; width: 100%; font-size: 0.85em; margin: 0.5em 0; }
  th, td { border: 1px solid #ccc; padding: 4px 8px; text-align: left; }
  th { background: #eee; position: sticky; top: 0; }
  td { font-family: monospace; }
  img { max-width: 100%; height: auto; border: 1px solid #ddd; }
  .grid3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 1em; }
  .grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 1em; }
  .nav a { margin-right: 1em; }
  .takeaway { background: #fff8dc; padding: 0.5em 1em; border-left: 4px solid orange; }
  .scrollable { max-height: 400px; overflow-y: auto; border: 1px solid #ccc; }
</style>
</head>
<body>

<h1>E-packet CPU follow-ups (2026-05-04)</h1>
<p>Non-ensemble CPU diagnostics over <code>P8A</code>, <code>E2B_TOP_N_STEP3200</code>, <code>E3_TOP_N_STEP6600</code>.
   Generated by <code>analysis/cpu_followups_2026-05-04/run_all_analyses.py</code>.</p>

<div class="nav">
<strong>Sections:</strong>
<a href="#auc">[AUC table]</a>
<a href="#corr">[Score correlations]</a>
<a href="#roc">[ROC curves]</a>
<a href="#operational">[Recall vs FPR]</a>
<a href="#histograms">[Score histograms]</a>
<a href="#scatter">[Score scatter]</a>
<a href="#per-method">[Per-method recall]</a>
<a href="#champion">[Method champions]</a>
<a href="#identity">[Per-identity FPR]</a>
<a href="#disagree">[Disagreements]</a>
</div>

<h2 id="auc">1. Cross-suite AUC (apples-to-apples)</h2>
<p>Each fake suite paired against <code>teams_real_all_dev</code> as negative class.
This gives the fundamental separability ceiling of each ckpt — independent of threshold.</p>
"""
    html += csv_to_html_table(OUT_DIR / "02b_cross_suite_auc.csv")
    html += """
<div class="takeaway">
<strong>Takeaway:</strong> P8A's viso AUC = 0.753, the highest of the 3 ckpts.
Scratch ckpts (E2B 0.682, E3 0.740) have INHERENTLY lower viso separability.
The 27% recall ceiling at FPR=10% reflects this — not threshold trickery.
On deeplive, BOTH scratch ckpts have +9-10pp AUC over P8A (0.965 vs 0.861).
</div>

<h2 id="corr">2. Per-frame score correlation (diagnostic only — not for ensembling)</h2>
<p>Pearson r between ckpts on the same frames. Low r → ckpts use different signal mechanisms.</p>
"""
    html += csv_to_html_table(OUT_DIR / "04_per_frame_score_correlation.csv")
    html += """
<div class="takeaway">
<strong>Takeaway:</strong> On viso fakes, P8A and E2B_3200 agree at r=0.30 only;
P8A and E3_6600 r=0.41. <strong>The ckpts use largely DIFFERENT viso-detection mechanisms.</strong>
Most extreme: deeplive fakes E2B vs E3 r=0.17 — completely different signal!
This refutes "scratch ckpts are doing the same thing as each other" intuition.
</div>

<h2 id="roc">3. ROC curves per fake suite</h2>
<div class="grid2">
"""
    for fs in fake_suites:
        p = FIG_DIR / f"roc_curve_{fs}.png"
        if p.exists():
            html += f'<div><h4>{fs}</h4><img src="{asset_url(p)}"></div>'
    html += "</div>"

    html += '<h2 id="operational">4. Operational view: recall vs FPR (zoomed 0-20%)</h2>'
    html += '<p>Vertical lines mark FPR=2/5/10%. This is the deployment-relevant region.</p>'
    html += '<div class="grid2">'
    for fs in fake_suites:
        p = FIG_DIR / f"recall_vs_fpr_{fs}.png"
        if p.exists():
            html += f'<div><h4>{fs}</h4><img src="{asset_url(p)}"></div>'
    html += "</div>"

    html += '<h2 id="histograms">5. Score-distribution histograms</h2>'
    html += '<p>Per ckpt: real (green) and fake (red) score densities. Visualizes class separation directly.</p>'
    for s in all_suites:
        p = FIG_DIR / f"score_histogram_{s}.png"
        if p.exists():
            html += f'<h4>{s}</h4><img src="{asset_url(p)}">'

    html += '<h2 id="scatter">6. Per-frame score scatter (P8A vs others)</h2>'
    html += '<p>Each dot is a frame. Diagonal = perfect agreement. Pearson r in title.</p>'
    for fs in fake_suites:
        html += f"<h3>{fs}</h3><div class='grid3'>"
        for pair in ["P8A_vs_E2B_3200", "P8A_vs_E3_6600", "E2B_3200_vs_E3_6600"]:
            p = FIG_DIR / f"scatter_{fs}_{pair}.png"
            if p.exists():
                html += f"<div><img src='{asset_url(p)}'></div>"
        html += "</div>"

    html += '<h2 id="per-method">7. Per-method recall table</h2>'
    html += '<p>Per (suite, method, FPR target), recall achieved by each ckpt.</p>'
    html += "<div class='scrollable'>"
    html += csv_to_html_table(OUT_DIR / "01_per_method_recall.csv", max_rows=300)
    html += "</div>"

    html += '<h2 id="champion">8. Method-by-method champion</h2>'
    html += '<p>Which ckpt wins each (suite, method, FPR floor) combination?</p>'
    html += "<div class='scrollable'>"
    html += csv_to_html_table(OUT_DIR / "05_method_champion.csv", max_rows=300)
    html += "</div>"

    html += '<h2 id="identity">9. Per-identity FPR concentration</h2>'
    html += '<p>For each ckpt × real suite: how concentrated are the false-positive identities?</p>'
    html += csv_to_html_table(OUT_DIR / "07_per_identity_fpr.csv")
    html += """
<div class="takeaway">
<strong>How to read:</strong> If <code>top10pct_offenders_share_of_total_fires</code> is high (>0.5), most FPs come
from a few identities. Low values mean FPs are spread evenly. Helps decide whether per-identity
allowlisting could clean up the worst offenders.
</div>"""

    html += '<h2 id="cluster-stats">9c. Statistical analysis of clusters (image-quality features)</h2>'
    html += '<p><strong>Top features distinguishing caught vs uncaught viso frames</strong> (Welch t-test + Cohen\'s d):</p>'
    html += csv_to_html_table(OUT_DIR / "14b_uncaught_vs_caught_ttest.csv")
    html += '<p style="margin-top:1em;"><strong>L1 logistic regression — feature importance for catched/uncaught:</strong></p>'
    html += csv_to_html_table(OUT_DIR / "14c_logistic_feature_importance.csv")
    html += '<p style="margin-top:1em;"><strong>Pairwise cluster differences</strong> (top feature per cluster pair, sortable):</p>'
    html += "<div class='scrollable'>"
    html += csv_to_html_table(OUT_DIR / "14d_pairwise_cluster_comparison.csv", max_rows=200)
    html += "</div>"
    html += """
<div class="takeaway" style="background: #ffe5e5; border-color: red;">
<strong>Mechanistic finding:</strong> The clusters are driven by IMAGE QUALITY, not random.
<ul>
  <li>Uncaught viso fakes are <strong>softer (Laplacian 42 vs 61)</strong> and brighter than caught ones — confirms the image-quality-shortcut hypothesis.</li>
  <li>P8A uniquely catches <strong>HIGH-EDGE</strong> viso fakes (Cohen's d=+1.68 vs uncaught on sobel_edge_mean).</li>
  <li>Scratch ckpts (E2B, E3) catch LOW-EDGE viso fakes that P8A misses — different image-quality regime.</li>
  <li>visomaster_enhanced_teams subtype is 19pp harder than visomaster_enhanced_raw (Teams pipeline smooths fakes).</li>
</ul>
<strong>Implication:</strong> Next packet hypothesis (untested): aug curriculum with sharpness reduction (target Laplacian 50-150 instead of native 250+) might break the shortcut.
</div>

<h2 id="viso-browse">9a. Viso fakes — score-space visualization (550 frames)</h2>"""
    html += '<p>Each viso fake plotted in score-space. Colored by which {ckpt} subset catches it at FPR=10%.<br>'
    html += 'Right plot: P8A score vs max(E2B, E3) score with FPR=10% threshold lines.</p>'
    p = FIG_DIR / "viso_score_space.png"
    if p.exists():
        html += f'<img src="{asset_url(p)}">'
    html += """
<div class="takeaway" style="background: #e0f0ff; border-color: blue;">
<strong>How to BROWSE the actual viso frames:</strong>
<ol>
<li>Run the viewer: <code>cd viewer && python3 server.py</code> (or your usual command).</li>
<li>Open the model dashboard, select run <strong>viso_uncaught</strong>.</li>
<li>Click <strong>Manifold Sample</strong> — t-SNE shows all 550 viso fakes; gray dots = uncaught by all 3 ckpts.</li>
<li>Click any point → image proxy fetches the actual GCS frame.</li>
<li>Click <strong>False Negatives</strong> on the same run → list view of viso fakes scoring below threshold.</li>
<li>Or select run <strong>e2b_3200</strong> / <strong>e3_6600</strong> and use the same buttons to see ckpt-specific failure modes.</li>
</ol>
Direct CSV access: <code>analysis/cpu_followups_2026-05-04/outputs/viso_uncaught_at_fpr10.csv</code> (364 frames, sortable by score).
</div>

<h2 id="threshold-relax">9b. Threshold relaxation curves — viso recall vs FPR floor</h2>"""
    html += '<p>How much does relaxing the FPR target unlock viso recall? Critical for understanding the "27% ceiling."</p>'
    html += csv_to_html_table(OUT_DIR / "11_threshold_relaxation_curves.csv", max_rows=30)
    html += """
<div class="takeaway" style="background: #fff8dc; border-color: orange;">
<strong>Reframing the "viso ceiling":</strong>
<ul>
<li>At FPR=10% (the prior framing), P8A holds the chain ceiling at 27%. Scratch ckpts are below.</li>
<li>At FPR=20%, P8A jumps to 57.6% viso recall. The 64% "invisible at FPR=10%" frames are largely catchable just below the 10% FPR threshold.</li>
<li>At FPR=30%, <strong>E3 (L14) reaches 87.5% viso recall</strong> — the highest viso of any single ckpt at any FPR floor. L14 has the most viso headroom but the score distribution is wider so it needs higher τ.</li>
<li>At FPR=50%, all 3 ckpts hit ~85-91% viso recall.</li>
</ul>
<strong>What this means for deployment:</strong> the production target FPR &lt; 5% gives all ckpts ~5-8% viso recall.
Which is unworkable. The deployment is gated by hitting viso recall &gt;&gt; 0 at FPR ≤ 5%, not by the FPR=10% number.
The "27% ceiling" framing was specific to the FPR=10% choice and may have biased prior packets toward the wrong axis.
</div>

<h2 id="frame-coverage">10. Frame coverage by ckpt-subset (FPR=10%)</h2>"""
    html += '<p>For each fake suite: which subset of {P8A, E2B_3200, E3_6600} catches each frame?</p>'
    html += csv_to_html_table(OUT_DIR / "10_frame_coverage_all_suites.csv", max_rows=50)
    html += """
<div class="takeaway" style="background: #ffe5e5; border-color: red;">
<strong>HUGE FINDING — viso ceiling is data-bounded:</strong> On visomaster_enhanced_macro_dev,
<strong>66.2% of viso fakes (364/550) are caught by NO ckpt at FPR=10%</strong>. Of the 186 viso fakes
that are caught, P8A catches 80% of them — the scratch ckpts contribute marginally.
The 27% recall ceiling at FPR=10% is mostly explained by ~2/3 of viso fakes being
"invisible" to all training axes we've tried.
<br><br>
<strong>Contrast: deeplive ceiling is essentially model-bounded.</strong> Only 1/545 deeplive frames is
caught by NONE — almost every deeplive fake gets some signal from at least one ckpt.
The deeplive lift from 43%→88% is calibration/separability, not coverage.
<br><br>
<strong>Implication for next steps:</strong> The viso ceiling cannot be broken by training-axis changes
on the current eval set. Either:
(1) the eval set has 2/3 mis-labeled or unsuitable frames (audit needed), OR
(2) the eval set has 2/3 frames whose fake-ness is upstream of all the features the
encoder can learn under standard training. Both interpretations point AWAY from "another packet."
</div>

<h2 id="disagree">11. Top per-video disagreements</h2>
<p>Top 200 videos where the 3 ckpts have the largest mean-score disagreement.</p>
<div class='scrollable'>"""
    html += csv_to_html_table(OUT_DIR / "06_per_video_disagreements.csv", max_rows=200)
    html += "</div>"

    html += """
<h2>Files</h2>
<ul>
  <li><strong>Input data</strong>: <code>analysis/cpu_followups_2026-05-04/raw_reports/</code> (171 frame CSVs)</li>
  <li><strong>Analysis outputs</strong>: <code>analysis/cpu_followups_2026-05-04/outputs/</code> (CSV tables)</li>
  <li><strong>Figures</strong>: <code>analysis/cpu_followups_2026-05-04/figures/</code> (PNG plots)</li>
  <li><strong>Generators</strong>: <code>run_all_analyses.py</code>, <code>02b_cross_suite_auc.py</code>, <code>08_visualizations.py</code></li>
</ul>
</body></html>
"""

    out = ANALYSIS_DIR / "INDEX.html"
    out.write_text(html)
    print(f"Wrote {out} ({len(html):,} chars)")


if __name__ == "__main__":
    main()
