steps:
# 1. Pull the latest image to be used as a cache source
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'docker pull us-docker.pkg.dev/train-cvit2/effort-detector/effort-detector:latest || exit 0'

# 2. Build the new image, using the pulled image as a cache
- name: 'gcr.io/cloud-builders/docker'
  timeout: 1800s # 30 minutes for this step alone
  args:
  - 'build'
  - '--cache-from'
  - 'us-docker.pkg.dev/train-cvit2/effort-detector/effort-detector:latest'
  - '--tag'
  - 'us-docker.pkg.dev/train-cvit2/effort-detector/effort-detector:latest'
  - '.'

# 3. Push the newly built image to the registry
images:
- 'us-docker.pkg.dev/train-cvit2/effort-detector/effort-detector:latest'

options:
  machineType: 'E2_HIGHCPU_8'